// svelte-spreadsheet/src/routes/spreadsheet/Spreadsheet.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Cell from './Cell.svelte';

	let cellContents: (number | string)[][] = [
		[1, 2, 3],
		[4, 5, 6],
		[7, 8, 9]
	];

	const persist = (): void => {
		fetch('/api/cells', {
			method: 'POST',
			headers: { 'Content-type': 'application/json' },
			body: JSON.stringify({ cells: cellContents })
		});
	};

	onMount(() => {
		fetch('/api/cells').then((res) =>
			res.text().then((s) => {
				const data = JSON.parse(s);
				if (data.cells) {
					cellContents = data.cells;
				}
			})
		);
	});
</script>

<table>
	<thead>
		<tr>
			<th></th>
			{#each cellContents[0] as _, i}
				<th>{String.fromCharCode(65 + i)}</th>
			{/each}
		</tr>
	</thead>
	<tbody>
		{#each cellContents as row, i}
			<tr>
				<th>{i + 1}</th>
				{#each row as cell, j}
					<Cell content={cell} onChange={(updated) => (cellContents[i][j] = updated)} />
				{/each}
			</tr>
		{/each}
	</tbody>
</table>
<button on:click={() => (cellContents = [...cellContents, Array(cellContents[0].length).fill(0)])}>
	+ row
</button>
<button on:click={() => (cellContents = cellContents.slice(0, -1))}> - row </button>
<br />
<button on:click={() => (cellContents = cellContents.map((row) => [...row, 0]))}>+ column</button>
<button on:click={() => (cellContents = cellContents.map((row) => row.slice(0, -1)))}
	>- column</button
>
<br />
<button
	on:click={(): void => {
		console.log(cellContents);
	}}
>
	Inspect
</button>
<br />
<button on:click={persist}>Save</button>

<style>
	table {
		width: 100%;
		border-collapse: collapse;
	}
	th {
		color: #505050;
		font-weight: normal;
		border: 1px solid #999;
		background: white;
		padding: 0;
		margin: 0;
	}
</style>

// next-spreadsheet/src/components/Spreadsheet.tsx
import React, { useEffect, useState } from "react";

import { CellContent } from "@/types/spreadsheet";

import styles from "@/styles/Spreadsheet.module.css";
import Cell from "./Cell";

export default function Spreadsheet() {
    const [cellContents, setCellContents] = useState<Array<Array<CellContent>>>([
        [1, 2, 3,],
        [4, 5, 6,],
        [7, 8, 9,],
    ]);

    const perpetuation = () => {
        // const data = JSON.stringify(cellContents);
        // window.localStorage.setItem("cells", data);

        fetch("/api/cells", {
            method: "POST",
            headers: { "Content-type": "application/json" },
            body: JSON.stringify({ cells: cellContents }),
        });
    };

    const setPersistedData = async () => {
        const response = await fetch("/api/cells");
        const persistedData = JSON.parse(await response.text());
        if (persistedData.cells) {
            setCellContents(persistedData.cells);
        }
    };

    //渡した関数をレンダリング実行後に実行させる
    useEffect(() => {
        // const persistedData = window.localStorage.getItem('cells');
        // if (persistedData) {
        //     setCellContents(JSON.parse(persistedData));
        // }

        //useEffectには返り値のないオブジェクトを指定する必要がある。
        //asyncを付けられるのはPromiseオブジェクトのみなので、Promiseが帰ってきてしまう為に直接指定は出来ない。
        //なので、一度ラップしてから渡す必要がある。
        setPersistedData();
        //第二引数が[]の場合、初回レンダリング時のみ実行
    }, []);

    const updateCell = (updated: CellContent, rowIndex: number, cellIndex: number) => {
        const updatedCellContents = [...cellContents];
        updatedCellContents[rowIndex][cellIndex] = updated;
        setCellContents(updatedCellContents);
    };

    const addRow = () => {
        setCellContents([
            ...cellContents,
            Array(cellContents[0].length).fill(0)
        ]);
    };
    const removeRow = () => {
        setCellContents(cellContents.slice(0, -1));
    };

    const addColumn = () => {
        setCellContents(
            cellContents.map(row => [...row, 0])
        );
    };
    const removeColum = () => {
        setCellContents(
            cellContents.map(row => row.slice(0, -1))
        );
    };

    return (
        <div className={styles.container}>
            <table>
                <tbody>
                    <tr>
                        <th></th>
                        {
                            //各列は前提として同じ長さなので、一列目の長さ分だけ見出しを生成すれば問題ない
                            //ただ、このままだとZの次がAAにならないので、変更は必要
                            cellContents[0].map((_, i) => (
                                <th>{String.fromCharCode(65 + i)}</th>
                            ))}
                    </tr>
                    {
                        cellContents.map((row, rowIndex) => {
                            return (
                                <tr>
                                    <th>{rowIndex + 1}</th>
                                    {
                                        row.map((cell, cellIndex) => (
                                            <Cell
                                                content={cell}
                                                onChange={(updated: CellContent) => updateCell(updated, rowIndex, cellIndex)}
                                            />
                                        ))
                                    }
                                </tr>
                            );
                        })
                    }
                </tbody>
            </table>
            <button onClick={addRow}>+ row</button>
            <button onClick={removeRow}>- row</button>
            <br />
            <button onClick={addColumn}>+ column</button>
            <button onClick={removeColum}>- column</button>
            <br />
            <button onClick={perpetuation}>Save</button>
            {/* <button onClick={() => window.localStorage.removeItem("cells")}>Reset</button> */}
        </div>
    );
};
